openapi: 3.0.3
info:
  title: Swagger LunaSpa - OpenAPI 3.0  
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
#Determine server port
servers:
  - url: http://localhost:4000

tags: #Tag for all functions
  - name: accounts
    description: accounts functions
  
paths:
  /accounts/login:
    post:
      tags:
        - accounts
      summary: Login
      description: Login
      operationId: login
      
      requestBody:
        description: Login information
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/LoginBody'
        required: true
      responses:
        200:
          description: Login successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login successfully"
                  result:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                      refresh_token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                      user:
                        type: object
                        properties:
                          _id: 
                            type: string
                            example: "1243879"
                          email:
                            type: string
                            example: "wxrdie@example.com"
                          name: 
                            type: string
                            example: "Wxrdie"                          
                          phone_number:
                            type: string
                            example: "+1234567890"
                          address:
                            type: string
                            example: "1234 Elm Street, Springfield, IL, 62704"
                          date_of_birth: #Can be null
                            type: string
                            format: date-time
                            nullable: true
                            example: "1990-05-15T08:30:00Z"
                          created_at:
                            type: string
                            format: date-time
                            example: "2023-01-01T12:00:00Z"
                          updated_at: #Can be null
                            type: string
                            format: date-time
                            nullable: true
                            example: "2024-02-28T15:45:00Z"
                          roles:
                            type: object
                            properties:
                              role_id:
                                type: string
                                example: "167bf2f13d29bdb85bedb392d"
                              role_name:
                                type: string
                                example: "user"

        422: #Happens when wrong username
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User not found"
                  result:
                    type: object
                    properties: {}
                  error:
                    type: object
                    nullable: true
                    properties: {}
        400: #Happens when wrong password
          description: Invalid password
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid password"
                  result:
                    type: object
                    properties: {}
                  error:
                    type: object
                    nullable: true
                    properties: {}
    
  /accounts/logout:
    post:
      tags:
        - accounts
      summary: Logout
      description: Logout
      operationId: Logout
      
      requestBody:
        description: Logout
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/LogoutBody'
        required: true
      responses:
        200:
          description: Logout successfully
          content:
            application/json:
              schema:
                type: object
                properties:                  
                  message:
                    type: string
                    example: "Logout successfully"                  
        401: #Happens when no refreshToken found
          description: User unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "refresh_token not found"
                  # result:
                  #   type: object
                  #   properties: {}       
      
  /accounts/register:
    post:
      tags:
        - accounts
      summary: Register
      description: Register new user
      operationId: Register      
      requestBody:
        description: Register
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/RegisterBody'
        required: true
      responses:
        200:
          description: Register successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Registered successfully"
                  result:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                      refresh_token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                      user:
                        type: object
                        properties:
                          _id: 
                            type: string
                            example: "1243879"
                          email:
                            type: string
                            example: "wxrdie@example.com"
                          name: 
                            type: string
                            example: "Wxrdie"                          
                          phone_number:
                            type: string
                            example: "+1234567890"
                          address:
                            type: string
                            example: "1234 Elm Street, Springfield, IL, 62704"
                          date_of_birth: #Can be null
                            type: string
                            format: date-time
                            nullable: true
                            example: "1990-05-15T08:30:00Z"
                          created_at:
                            type: string
                            format: date-time
                            example: "2023-01-01T12:00:00Z"
                          updated_at: #Can be null
                            type: string
                            format: date-time
                            nullable: true
                            example: "2024-02-28T15:45:00Z"
                          roles:
                            type: object
                            properties:
                              role_id:
                                type: string
                                example: "167bf2f13d29bdb85bedb392d"
                              role_name:
                                type: string
                                example: "user"