openapi: 3.0.3
info:
  title: Swagger LunaSpa - OpenAPI 3.0  
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
#Determine server port
servers:
  - url: http://localhost:4000

tags: #Tag for all functions
  - name: user
    description: User functions
  
paths:
  /user/login:
    get:
      tags:
        - user
      summary: Login
      description: Login
      operationId: login
      
      requestBody:
        description: Login information
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/LoginBody'
        required: true
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "Login successful"
                  result:
                    type: object
                    properties:
                      token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                      refreshToken:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        404:
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: "User not found"
                  result:
                    type: object
                    properties: {}
    
  /user/me:
    get:
      tags:
        - user
      summary: Lấy thông tin user
      description: Lấy thông tin user
      operationId: getMe
      security:
        - BearerAuth: []
      responses:
        default:
          description: Lấy thông tin user thành công
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/User'