import { config } from 'dotenv'
import { StringValue } from 'ms'

config()

export const envConfig = {
  port: (process.env.PORT as string) || '4000',
  dbUsername: process.env.DB_USERNAME as string,
  dbPassword: process.env.DB_PASSWORD as string,
  dbName: process.env.DB_NAME as string,
  dbAccountsCollection: process.env.DB_ACCOUNTS_COLLECTION as string,
  dbResourcesCollection: process.env.DB_RESOURCES_COLLECTION as string,
  dbRolesCollection: process.env.DB_ROLES_COLLECTION as string,
  dbRefreshTokensCollection: process.env.DB_REFRESH_TOKENS_COLLECTION as string,
  dbProductCategoriesCollection: process.env.DB_PRODUCT_CATEGORIES_COLLECTION as string,
  dbServiceCategoriesCollection: process.env.DB_SERVICE_CATEGORIES_COLLECTION as string,
  dbDevicesCollection: process.env.DB_DEVICES_COLLECTION as string,
  dbProductsCollection: process.env.DB_PRODUCTS_COLLECTION as string,
  dbServicesCollection: process.env.DB_SERVICES_COLLECTION as string,
  dbServicesProductsCollection: process.env.DB_SERVICES_PRODUCTS_COLLECTION as string,
  dbConditionsCollection: process.env.DB_CONDITIONS_COLLECTION as string,
  dbConditionProductsCollection: process.env.DB_CONDITION_PRODUCTS_COLLECTION as string,
  dbConditionServicesCollection: process.env.DB_CONDITION_SERVICES_COLLECTION as string,
  dbUserProfilesCollection: process.env.DB_USER_PROFILES_COLLECTION as string,
  dbStaffProfilesCollection: process.env.DB_STAFF_PROFILES_COLLECTION as string,
  dbStaffSlotsCollection: process.env.DB_STAFF_SLOTS_COLLECTION as string,
  dbOrdersCollection: process.env.DB_ORDERS_COLLECTION as string,
  dbOrderDetailsCollection: process.env.DB_ORDER_DETAILS_COLLECTION as string,
  dbTransactionsCollection: process.env.DB_TRANSACTIONS_COLLECTION as string,
  dbFavoritesCollection: process.env.DB_FAVORITES_COLLECTION as string,
  dbBranchesCollection: process.env.DB_BRANCHES_COLLECTION as string,
  dbReviewsCollection: process.env.DB_REVIEWS_COLLECTION as string,
  dbBranchServicesCollection: process.env.DB_BRANCH_SERVICES_COLLECTION as string,
  dbBranchProductsCollection: process.env.DB_BRANCH_PRODUCTS_COLLECTION as string,
  dbServiceProductsCollection: process.env.DB_SERVICE_PRODUCTS_COLLECTION as string,
  dbRewardPointsCollection: process.env.DB_REWARD_POINTS_COLLECTION as string,
  dbVouchersCollection: process.env.DB_VOUCHERS_COLLECTION as string,
  jwtSecret: process.env.JWT_SECRET as string,
  passwordSecret: process.env.PASSWORD_SECRET as string,
  accessTokenLife: process.env.ACCESS_TOKEN_EXPIRES_IN as StringValue,
  refreshTokenLife: process.env.REFRESH_TOKEN_EXPIRES_IN as StringValue,
  emailVerificationTokenLife: process.env.EMAIL_VERIFY_TOKEN_EXPIRES_IN as StringValue,
  forgotPasswordTokenLife: process.env.FORGOT_PASSWORD_TOKEN_EXPIRES_IN as StringValue,
  jwtSecretAccessToken: process.env.JWT_SECRET_ACCESS_TOKEN as string,
  jwtSecretRefreshToken: process.env.JWT_SECRET_REFRESH_TOKEN as string,
  jwtSecretEmailVerifyToken: process.env.JWT_SECRET_EMAIL_VERIFY_TOKEN as string,
  jwtSecretForgotPasswordToken: process.env.JWT_SECRET_FORGOT_PASSWORD_TOKEN as string,
  awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID as string,
  awsSecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY as string,
  awsRegion: process.env.AWS_REGION as string,
  sesFromAddress: process.env.SES_FROM_ADDRESS as string,
  clientUrl: process.env.CLIENT_URL as string,
  googleClientId: process.env.GOOGLE_CLIENT_ID as string,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
  googleRedirectUri: process.env.GOOGLE_REDIRECT_URI as string,
  clientRedirectGoogleCallback: process.env.CLIENT_REDIRECT_GOOGLE_CALLBACK as string,
  clientRedirectFacebookCallback: process.env.CLIENT_REDIRECT_FACEBOOK_CALLBACK as string,
  facebookClientId: process.env.FACEBOOK_CLIENT_ID as string,
  facebookClientSecret: process.env.FACEBOOK_CLIENT_SECRET as string,
  facebookRedirectUri: process.env.FACEBOOK_REDIRECT_URI as string,
  facebookAppId: process.env.FACEBOOK_APP_ID as string,
  s3Bucket: process.env.S3_BUCKET as string,
  s3Region: process.env.S3_REGION as string,
  s3AccessKeyId: process.env.S3_ACCESS_KEY_ID as string,
  s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY as string,
  stripeSecretKey: process.env.STRIPE_SECRET_KEY as string,
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET as string,
  stripeCurrency: process.env.STRIPE_CURRENCY as string
}
